### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by SimurgAnka** [TALUAtGitHub/android_kernel_sony_msm8994#1]
Hi i saw your kernel changes,is this changes will be merged for tarkzim's sources ? You know  this kernel needs many performance and battery optimization changes, i hope this changes can improve general performance and heating problems. thanks for development.

**Comment by TALUAtGitHub** [comment]
Hi,
I've been considering opening a pull request for my new changes. I probably will do so once I make a few more.

**Comment by SimurgAnka** [comment]
Okay thank you so much
